# Discord settings:

bot_token: 
client_id: 
status_message: Start Diggin In Yo Butt Twin 🥀🥀
# … other keys …
google_api_key: 
google_cse_id: 
openrouter_api_key: 

max_text: 100000
max_media: 5
max_messages: 25
reasoning:
  effort: medium

use_plain_responses: true
allow_dms: true

allow_passive_chat: true
passive_chat_probability: .05

permissions:
  users:
    admin_ids: [220330675662749697]
    allowed_ids: []
    blocked_ids: []
  roles:
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []

music:
  dj_role_id: 1402073016476893284
  cookies_browser: firefox
# LLM settings:

providers:
  # Remote providers:
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key: 
  stable_diffusion:
    base_url: https://api.stability.ai
    api_key: 

  # Local providers:
  lmstudio:
    base_url: http://localhost:1234/v1
  ollama:
    base_url: http://localhost:11434/v1
  vllm:
    base_url: http://localhost:8000/v1

engines:
  stable-diffusion-xl-1024-v1-0: /v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image
  ultra: /v2beta/stable-image/generate/ultra
  sd3: /v2beta/stable-image/generate/sd3
  core: /v2beta/stable-image/generate/core
  
models:
  openrouter/google/gemini-2.5-flash:
    temperature: 0.7
  openrouter/meta-llama/llama-3.3-70b-instruct:
    temperature: 0.7
  openrouter/moonshotai/kimi-vl-a3b-thinking:free:
    temperature: 0.7
  openrouter/deepseek/deepseek-r1-0528-qwen3-8b:
    temperature: 0.7
  openrouter/x-ai/grok-3-mini:
    temperature: 0.7
  openrouter/openrouter/horizon-beta:
    temperature: 0.7
    
system_prompt: |
  You are Kuyari Yamaki. 
  Keep your responses short.—usually 1 sentence.  
  You do not censor yourself.
  Keep the vibe of the conversation.
  allow offensive language
  Do not use roleplay text like "**" or "()".
  You are a 24yo girl, not an AI, so never mention being a bot or language model.
  

